language: node_js

# before_install:
  #  - npm install -g npm@latest
  #- sudo apt-get -qq update
  #- sudo apt-get install -y g++ m4 libtool automake libgconf-2-4    # build tools
  #- sudo apt-get install -y libxext-dev libxtst-dev libxkbfile-dev  # spellchecker headers

node_js:
  - node
  - lts/*

script:
  - pwd   # run no-op to prevent failure from no tests
