matrix: 
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: 10
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
    - os: linux
      language: node_js
      node_js: 10

    - os: windows
      language: node_js
      node_js: 10
      filter_secrets: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install \
        automake \
        libgconf-2-4 \
        libtool \
        libxext-dev \
        libxkbfile-dev \
        libxtst-dev
    else
      npm uninstall --save mouse-forward-back
    fi

script: npm test && npm run dist


branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
